name: "Release"
on:
  workflow_call:
defaults:
  run:
    shell: bash

jobs:
  release:
    name: "Semantic Release"
    runs-on: ubuntu-latest
    
    steps:
      - uses: actions/checkout@v3
        with:
          fetch-depth: 0
          persist-credentials: false
      
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'npm'
          cache-dependency-path: '**/package-lock.json'
      
      - name: "Obtain Github App token"
        id: app-token
        uses: getsentry/action-github-app-token@v2.0.0
        with:
          app_id: ${{ secrets.BOT_APP_ID }}
          private_key: ${{ secrets.BOT_APP_PRIVATE_KEY }}

      - name: "Clean install dependencies"
        run: npm ci

      - name: "Build"
        run: npm run build

      - name: "Execute Semantic Release"
        run: npx semantic-release
        env:
          GITHUB_TOKEN: ${{ steps.app-token.outputs.token }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}

  cache-purge:
    name: "Purge branch Actions cache"
    needs: release
    if: ${{ github.event_name == 'pull_request' }}
    runs-on: ubuntu-latest
    
    steps:

      - name: "Delete Branch Cache Action"
        uses: snnaplab/delete-branch-cache-action@v1.0.0
        with:
          # Specify explicitly because the ref at the time of merging will be a branch name such as 'main', 'develop'
          ref: refs/pull/${{ github.event.number }}/merge
          github-token: ${{ secrets.GITHUB_TOKEN }}
